### ISSUE TITLE
Work with audio notes

### ISSUE THREAD

**Issue by ihanick** [nuttyartist/notes#100]
I'm not always close to my computer than I have an important thing to note.
Mobile devices are not comfortable for inserting 1-3 minutes speech and a sound recorder (digital recorder or smartphone application) could resolve this issue.

So, at evening I'm converting almost all records to text notes, but it will be great to attach files from corresponding day to specific note (or even be able to listen these audio notes).

It could be like an email in popular web clients: some rich formatted text and links to attached files with "preview" feature for files.

**Comment by nuttyartist** [comment]
Hey @ihanick, 

We surely plan on incorporating media in Notes in the future. This includes recording and attaching audio, links, images, and videos, (and maybe even pdf's). We want the because we want Notes to fulfill its true vision of being a place where all of you ideas, thoughts, and files are at. But this will require a complete reworking of how the notes editor work, and it's quite challenging and require changing the tool we use for making the note's editor (QTextEdit) from the ground up - we would (probably) need to change to HTML or something.

So it's a bit in the distant future, but it's on our wish-list.
