### ISSUE TITLE
Make location of notes Dropbox folder

### ISSUE THREAD

**Issue by klequis** [nuttyartist/notes#109]
Is it possible to change the location where notes are stored to be ~/Dropbox so they are backed-up?

Thank you

**Comment by dddw** [comment]
I have a master-slave setup with my get-notes via a cron task. A simple backup would be to add to your crontab"

> ## notes master
> 45 * * * * rsync -av ~/.config/Awesomeness/* ~/Dropbox/11NOTES/Reference/Awesomeness/ 


See also for different platforms: https://github.com/nuttyartist/notes/issues/80

**Comment by theshadowx** [comment]
I think in the next versions we are going to add an option to choose where to put the database file.

Till then : 
you can use what use what @dddw described.

or to follow these steps

## Notes App (Notes database) --> DropBox ##

1. Depending on your OS you'll find the files in one of the locations mentioned here #80
2. move **notes.db** to your  ~/Dropbox
3. create a shortcut (symbolic link) of this file
4. move the shortcut to the location in step 1
5. rename the shortcut to notes.db

now each time you modify something in Notes app it will be synced in dropbox.

---

## DropBox (Notes database) --> Notes App ##

If you use another computer that is linked to the dropbox and contains notes.db:
I think it's better to install the same version of Notes app from which the database was used.

1. After installing Notes app, open it so that it will generate the database and the configuration file.
2. Close the app.
3. Go to the ~/Dropbox folder and create a shortcut (symbolic link) of notes.db
4. Open the Notes app folder #80 and delete the existing notes.db .
5. move the shortcut to notes folder #80 .

When you'll open Notes app you'll have your notes synced with dropbox.

**Comment by dddw** [comment]
^ that is an excellent solution, however I do get weird entries then. Newer entries start with @string. 
![Uploading 2017-02-27 09.59.18 pm.png…](cross platform issue?)

**Comment by theshadowx** [comment]
@dddw  what do you have as note, is there any script stored as note?

**Comment by dddw** [comment]
I use the program to store notes with snippets of scripts, but that wasn't an issue before making symbolic links. seems to happen with only new notes after the symbolic linking.

**Comment by theshadowx** [comment]
is it possible to share these snippets for test purpose

**Comment by dddw** [comment]
I'll have to prune it, since I also use it for work.
Then I can make a copy, so you might replicate the problem.

**Comment by theshadowx** [comment]
@dddw Do you still have this issue ? I haven't yet received the snippets in order to work on them to solve this bug.

**Comment by dddw** [comment]
Oh hi, yes I do. Sory forgot about this bug (getting used to it)

Here is a snipper from my Notes.ini


`content="@String(@String(@String(Foo apache\n=========\n\n/usr/sbin/apachectl -S\0\n\n)))"`
`dateCreated=2017-03-09T14:22:50`
`dateEdited=2017-03-09T14:23:09`

`[noteID_134]`
`content="@String(reserverd disk ruimte\n=============\ntune2fs -m 1 /dev/sdXY\n(verander sdXY in diskname, bijv: vda2 )\n\nNIET doen op /var /tmp /boot /root\n\nhttp://unix.stackexchange.com/questions/7950/reserved-space-for-root-on-a-filesystem-why#7965\n\n\0)))"`
`dateCreated=2017-03-22T16:31:42`
`dateEdited=2017-04-07T17:47:51`

`[noteID_135]`
`content="@String(@String(@String(mount encrypted LVM disk\n===================\nsudo mkdir /mnt/WHATUWANT\n\nvgscan\nvgchange -a y\n\0\n\nmount /dev/volumegroup/logicalvolume /mnt/somewhere\n\nas root and all the partitions should have devices created in the form /dev/volumegroup/logicalvolume, which ``you can then mount in the usual way:\n\nexample:\n\n\0\n\nhttp://www.tuxradar.com/answers/296)))"`

**Comment by theshadowx** [comment]
Is it possible to send the snippet that generated this. I mean the text that was pasted in the textfield. because I can't go farther with the ones you posted.

**Comment by dddw** [comment]
no, apparently I edited that entry.
But here are others:
`@String(@String(@String(Foo apache`
`=========`

`/usr/sbin/apachectl -S`

`)))`

I do see a weird character now I pasted it here, it's not visible in the progam though. Could be the cause?

**Comment by theshadowx** [comment]
I tried to reproduce this problem, but was not able to.

I think in the next release, this issue will be solved, as we are going to use Sqlite database. Thus, this issue won't appear as data won't be in plain text. (Please be patient ;)  )

**Comment by theshadowx** [comment]
hi @dddw  
we have released a new version of Notes, Could you please check if this method (Dropbox) works well with this new version.

**Comment by dddw** [comment]
OK, cool! I'll check it out next week

**Comment by theshadowx** [comment]
@dddw  I need your feedback :)

**Comment by dddw** [comment]
ok ok, I haven't switched to the new vershion yet (don't want to break my current notes!)
But I'll give it a try. Will have to do an alien rebuild for fedora first though.

**Comment by theshadowx** [comment]
@dddw thanks
