### ISSUE TITLE
No resizing on the window

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#17]
Some operating systems don't support native resizing on frameless windows.
Good guys: **Linux DE's:** Unity **Windows:** Windows 10
Bad guys: **Linux DE's:** Elementary OS,  KDE, Gnome, Deepin, Linux Mint **Windows:** Windows 7, Windows 8 **Mac:** Yosemite

**Comment by nuttyartist** [comment]
This issue should get solved on the side of the window manager, so only the operating system developers can solve that bug.

We do have the option to try to build resize mechanism by ourselves, but after trying, the code looks nasty and it doesn't work well, it isn't consistent and just doesn't feel native and fluid.

**Comment by moribellamy** [comment]
I came fishing through the issues to see if I could find this one :). I'm on ubuntu 18.04, using default gnome + gnome-shell. I installed the app through the snap store.

Workaround: While I can't get the resize icon by the typical method of hovering, I can use ALT+F8 to resize.

One thing I don't get though...when I build and run from source (3447b6f1fa5b50a85e1d7d884edc2423a2fdab85) the resize icon _does_ show up through normal means. So I'm not sure what's different. The color scheme also seems different -- note background are translucent blue rather than yellow.

**Comment by nuttyartist** [comment]
Hey @moribellamy!

The reason for that is probably due to the snap store having an old version of Notes. We tried to contact the developer who helped us upload it to the store (@dplanella) so we can update it to the latest version but to no success.

Anyways, yes! We eventually developed our own custom resizing and shadow mechanism (thanks to @theshadowx) for our newest version (1.0.0).

I'm not sure what version is on the snap store but we improved quite a bit since previous releases, including redesigned color scheme and UI, new database structure, custom window rendering (shadow+resizing), system tray icon with instant launch, automatic updates, export/import functions, and a refined experience with bugs fixed. You can learn more on our blog: https://www.get-notes.com/blog

So I highly recommend you to grab the latest snap from our app and install Notes using it. That will give you the latest version and the best experience.
