### ISSUE TITLE
Icon on Linux

### ISSUE THREAD

**Issue by ryands17** [nuttyartist/notes#178]
The icon looks very bad on linux

**Comment by theshadowx** [comment]
Could you share screenshot please.

**Comment by nuttyartist** [comment]
@ryands17 What do you mean, is it ugly specifically on Linux because of some bug? Or is it just doesn't fit the look of your Linux distribution?

Like @theshadowx said, a screenshot will be helpful.

Overall, we do think we can do better on the design of our Icon, that's why we have a section dedicated to finding a designer to make a better icon on our website.

**Comment by ryands17** [comment]
It looks like this
![notes_icon](https://user-images.githubusercontent.com/19697099/31307798-b6d93aa4-ab88-11e7-8b5a-609c5cd42640.png)

I am using Manjaro 17

**Comment by nuttyartist** [comment]
That's really weird. What exactly is that? I mean, is that at the task manager area? Desktop?

**Comment by ryands17** [comment]
Its look like this on the Desktop dock

**Comment by nuttyartist** [comment]
@ryands17 Have you had any sort of weird experiences like this with other apps? Maybe it's related to your graphics card driver, or maybe it's something with the OS and Qt.
