### ISSUE TITLE
Update snap to 1.0.0

### ISSUE THREAD

**Issue by Ads20000** [nuttyartist/notes#185]
The snap in the store (`snap info notes`) is `0.9.0~gitb6e3b34 (4)` not `1.0.0`. Please can you push the snap to the store so that those that have it are automatically updated?

With the snap, just use (with `snapcraft` installed (`sudo snap install snapcraft --candidate`)):
`snapcraft push notes_1.0.0_amd64.snap`
`snapcraft release notes 5 edge`
test with `sudo snap install notes --edge` (check the version in `edge` is correct with `snap info notes`)
if it works, then use `snapcraft release notes 5 stable`

[Source](https://docs.snapcraft.io/build-snaps/publish)

You may also want to get automatic builds going with build.snapcraft.io :)

**Comment by theshadowx** [comment]
Hi @Ads20000 
We want to update it, but we don't have the credentials to allow us to do it.

@dplanella, please could you do it, or pass the account (usrname/pw) to @nuttyartist. thanks

**Comment by bjorn** [comment]
Still not uploaded now that we have the credentials? Should be a quick one to push since the snap is already done.

**Comment by nuttyartist** [comment]
You're right! I just updated the page with new info, but I don't have a Linux machine ready (seems like i need one) Can I give you my user credentials over email and you'll push it? 

Also, some really awesome metrics that I only now noticed. Since we don't track analytics of active users it's cool to see that we have more than 15K weekly active users (only with snap on ubuntu). And the number is growing.

![Screen Shot 2020-02-27 at 12 21 00 PM](https://user-images.githubusercontent.com/16375940/75435464-bc0bb000-595b-11ea-8f41-94877ff4c6c2.png)

![Screen Shot 2020-02-27 at 12 21 13 PM](https://user-images.githubusercontent.com/16375940/75435473-bf9f3700-595b-11ea-90ae-cb35b17d96a0.png)

**Comment by theshadowx** [comment]
The snap folder in packages should be moved to the root folder so that snapcraft can take it into considerarion

**Comment by nuttyartist** [comment]
Can I send you over my snapstore account credentials?

**Comment by theshadowx** [comment]
Also please wait till the snapcraft is updated. The version 1.0.0 uses sqlite database which won't work with the current snapcraft script

**Comment by theshadowx** [comment]
If you want

**Comment by nuttyartist** [comment]
Oh ok, so we shall wait for 1.5.0?

**Comment by theshadowx** [comment]
Ya

**Comment by bjorn** [comment]
> The version 1.0.0 uses sqlite database which won't work with the current snapcraft script

Ah, you mean the snap that is up at https://github.com/nuttyartist/notes/releases/tag/v1.0.0 is actually broken?

**Comment by bjorn** [comment]
> Also, some really awesome metrics that I only now noticed. Since we don't track analytics of active users it's cool to see that we have more than 15K weekly active users (only with snap on ubuntu). And the number is growing.

Those are some awesome statistics! In comparison, the Tiled snap has little over 1K weekly active users.

But, do I understand correctly that 0.9 used an entirely different way to store the notes? Was it tested whether upgrading will keep user's notes intact? It's especially important with 15K users. :-)

> Can I send you over my snapstore account credentials?

I believe it should be possible to add collaborators somewhere, likely at https://dashboard.snapcraft.io/snaps/notes/collaboration/.

**Comment by theshadowx** [comment]
@bjorn before, data was stored using QSettings to store current notes in notes.ini and removed notes in trash.ini .
Using sqlite makes things more manageable.
There are functions in Mainwindow thta checks if these two files exist they will  migrate  data contained in those files to notes.db. these files are not removed but a suffix is added to them "old" so that the use can still access to notes, in case something didn 't work well.

**Comment by nuttyartist** [comment]
> But, do I understand correctly that 0.9 used an entirely different way to store the notes? Was it tested whether upgrading will keep user's notes intact? It's especially important with 15K users. :-)

Indeed. We made sure to take care of it automatically as @theshadowx said :)

I posted some more metrics on Gitter: https://gitter.im/nuttyartist/notes
