### ISSUE TITLE
it's better to show confirmation before deleting, or implement a recycle bin so that deleted notes can be restored

### ISSUE THREAD

**Issue by mohamed-selim-a** [nuttyartist/notes#247]

**Comment by nuttyartist** [comment]
"recycle bin so that deleted notes can be restored"

This is what we'll do, we'll create a Trash folder where people could easily restore there deleted notes. Right now, any note you delete is not really deleted, it just goes to a hidden trash folder that the UI doesn't show yet. We gonna implement that in Version 2.0.0.
