### ISSUE TITLE
Hitting 'Ctrl + del' deletes the whole note

### ISSUE THREAD

**Issue by bhavya-quo** [nuttyartist/notes#255]
I have a habit of deleting multiple words using ctrl + delete and doing so results in the entire note being deleted. Atleast there should be a prompt before the user is about to delete the note so that we can review our actions.

**Comment by theshadowx** [comment]
Thanks for reporting this issue.
It is a known issue #214 .  it was fixed in #235   .it will be published in version 1.5 .

If you want to access to the deleted notes you can access to sqlite database Notes.db and in trash table you 'll find all your deleted notes.

**Comment by nuttyartist** [comment]
Hello, @bhavya-quo. We are aware of how bad of user experience it is that people can mistakenly delete their notes, and as @theshadowx said, we fixed this issue by changing the keyword shortcut. We're also working on a Trash folder feature as fast as we can so people could easily restore their lost notes.

That said, as @theshadowx mentioned, we never really delete your notes when you delete them.
We keep them in a safe place - a trash folder - it's just not visible in the graphical user interface.
This file can be found on:
**Windows** : C:\Users\user\AppData\Roaming\Awesomeness
**Linux**       : /home/user/.config/Awesomeness/ or /home/snap/notes/x1/.config/Awesomeness (using snap)
**Mac**         : /home/.config/Awesomeness/
The database file name is notes.db.

You'll need a special app in order to read the content of this file probably.
Note that this file contains all your notes data so you don't want to modify and mistakenly damage it.
So copy the file notes.db to a safe place. Copy -- don't move it.

And I may suggest you download this app https://sqlitebrowser.org in order to read the content of this file.
After downloading and installing, launch the app and click "Open Database".
Find the notes.db file on your Desktop and open it.
Then click on the "Browse Data" tab on the left pane.
There you can change the selection in the "table" combo box to "deleted_notes".
You should see there all of your deleted notes data.

Please let me know if it was helpful.
If you need any more help, don't hesitate to ask.
We are here to help you.

**Comment by bhavya-quo** [comment]
@nuttyartist Thanks for such a detailed explanation. I hope there are more enhancements in 1.5.
I started as an end user but now I can't resist to take look under the hood. Hoping to become a collaborator soon!

**Comment by nuttyartist** [comment]
Awesome! You are very welcome to join our development of Notes. If you're just getting started with programming we marked issues that might be relevant for you with a "good first issue" [tag](https://github.com/nuttyartist/notes/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).
