### ISSUE TITLE
Updating deb packaging for version 1.5

### ISSUE THREAD

**Issue by theshadowx** [nuttyartist/notes#260]
deb files to be updated to generate deb package

**Comment by nuttyartist** [comment]
And we should change all the version as here also https://github.com/nuttyartist/notes/commit/bb64fe95d820b5d07379d5b2fc238c4030b57118, right?

**Comment by theshadowx** [comment]
yes

**Comment by theshadowx** [comment]
just next time for 2.0.0, we should create a branch 2.0.0 and but all the commits done after 1.5.0.
so that it would be easier to mention the modifications done in the changelog an also in the release.

Then each new version should have a branch. specific to it containing all the commits done in that version

**Comment by bjorn** [comment]
> Then each new version should have a branch. specific to it containing all the commits done in that version

I would personally suggest to do further development on `master` instead of `dev`. GitHub defaults to development on `master`, so it's a little less confusing in my opinion. Then, we'd create a branch on each new features release, just for potential patch releases. At least this works well for Tiled.

> And we should change all the version as here also [bb64fe9](https://github.com/nuttyartist/notes/commit/bb64fe95d820b5d07379d5b2fc238c4030b57118), right?

I've opened up #261 based on this change, so we can see what the autobuilds say.

> deb files to be updated to generate deb package

Did you open this issue because there is anything besides the version bump to be done?

**Comment by theshadowx** [comment]
> Did you open this issue because there is anything besides the version bump to be done?

Well yes, but there is a bug, at least in Ubuntu 18.04 the "always stay on top" doesn't work.
It's not a big issue, do you think we should fix it in this version ?

**Comment by bjorn** [comment]
> Well yes, but there is a bug, at least in Ubuntu 18.04 the "always stay on top" doesn't work.
> It's not a big issue, do you think we should fix it in this version ?

I'd say if it was already broken in 1.0 then there's no need to fix it before 1.5. But, we should open an issue about that such that to be aware of it and maybe fix it later.

It also has nothing to do with Debian packaging. What needs to be done for Debian packaging besides the version bump?

**Comment by theshadowx** [comment]
There is conflict in the license used, here it shows mpl2, but in deb it's gpl2 , I think this was because deb doesn't recognize mpl2, I m not sure

**Comment by nuttyartist** [comment]
> just next time for 2.0.0, we should create a branch 2.0.0 and push to it all the commits done after 1.5.0.
so that it would be easier to mention the modifications done in the changelog an also in the release.

@theshadowx Sure.

> I would personally suggest to do further development on master instead of dev. GitHub defaults to development on master, so it's a little less confusing in my opinion. Then, we'd create a branch on each new features release, just for potential patch releases. At least this works well for Tiled.

@bjorn I like the way we set up, it makes a distinction between stable, experimental and future features. But your idea will make it so updates in the future will get to users much faster because PR's will be "patches" to the master. So I'm turned. Maybe we should do it after releasing 2.0.0? @theshadowx What do you think?

> I'd say if it was already broken in 1.0 then there's no need to fix it before 1.5. But, we should open an issue about that to maybe fix it later.

I agree. I will reply in #262.

> Also there is conflict in the license used, here it shows mpl2, but in deb it's gpl2 , I think this was because deb doesn't recognize mpl2, I m not sure

@theshadowx That's weird. Where do you see it? When you install it with the package manager?

**Comment by theshadowx** [comment]
> @theshadowx That's weird. Where do you see it? When you install it with the package manager?

my mistake, I checked and it's MPL-2

**Comment by nuttyartist** [comment]
@theshadowx Since deb packaging is the last thing remaining for v1.5, do you think you can give a go at updating the dependencies?

**Comment by theshadowx** [comment]
@nuttyartist  sure, I will updatedeb packaging

**Comment by nuttyartist** [comment]
@theshadowx Did you progress on this?

**Comment by nuttyartist** [comment]
Hey, @theshadowx, can you help with this?
