### ISSUE TITLE
"Always on top" not working in Ubuntu

### ISSUE THREAD

**Issue by theshadowx** [nuttyartist/notes#262]
This feature has been added post 1.0.0
In Ubuntu 18.04, "Always on top" is not working,  even when the option is checked, the gui still gets hidden by others.

**Comment by bjorn** [comment]
Documentation for `Qt::WindowStaysOnTopHint` states "Note that on some window managers on X11 you also have to pass Qt::X11BypassWindowManagerHint for this flag to work correctly."

I gave it a quick try on Ubuntu 19.10, where this feature also isn't working, and it indeed works when setting `Qt::X11BypassWindowManagerHint` as well. However, there are unwanted side-effects:

* The standard shortcut Alt+F4 no longer works to close the window.
* Active window looks like inactive (no colored buttons in top left).
* Modifier key for quickly moving / resizing a window no longer works.

I wonder if this feature is really so important, or whether it may be better to just hide it on Linux.

Another thing I noticed is that the `m_alwaysStayOnTop` member does not appear to get initialized.

**Comment by theshadowx** [comment]
> I wonder if this feature is really so important, or whether it may be better to just hide it on Linux.

This feature helps the user to have the app ready to take notes while doing other things in other apps.

**Comment by bjorn** [comment]
Yeah, I think that'd be better as well. The macOS look is rather out of place on other systems anyway.

**Comment by nuttyartist** [comment]
> I gave it a quick try on Ubuntu 19.10, where this feature also isn't working, and it indeed works when setting Qt::X11BypassWindowManagerHint as well. However, there are unwanted side-effects:
>
> The standard shortcut Alt+F4 no longer works to close the window.
Active window looks like inactive (no colored buttons in top left).
Modifier key for quickly moving / resizing a window no longer works.

That is a lot of problems just for that feature, which obviously not worth it.
Let's set this bug aside from v1.5.0.

I'm out of touch with the Linux world for quite some time, but I started Notes especially because there wasn't any elegant and simple app to take notes on Linux. I think many users appreciate that. The Linux world is messy, scattered with many different DE's, styles, and configurations. I would like to see how Notes look like without our custom decorations on different Linux distributions and then decide.

I also thought about an approach that will customize Notes based on the DE it is running on, in order to give each DE the best experience we can. @theshadowx I think we started doing something like this but I forgot where. For some, our default configuration is working well (coincide with our aesthetics) and for some, it's ruining.

**Comment by theshadowx** [comment]
@nuttyartist it's better to leave the decoration to DE, as long as Qt doesn't have api to interface with DE.
The mechanism of the app resizing (I know it was me that wrote it), right now, is awful.

**Comment by nuttyartist** [comment]
@theshadowx I wouldn't say it's awful, but it's certainly doesn't feel native and gives a worse experience. @theshadowx I will take this into consideration.

**Comment by Waqar144** [comment]
> I think it would be better to just use the host window decoration instead of overriding it, and leave to the user to choose the theme to be applied

It would solve other issues as well, that may not have been encountered yet.
