### ISSUE TITLE
macOS Packaging: auto sign, auto notarize, create Universal app for arm chips

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#411]
We need to add 3 more steps to our app packaging for macOS:

- [x] Automatic code sign
- [x] Automatic notarization
- [x] Creating Universal app for native support of arm chips (M1, etc...)

**Comment by nuttyartist** [comment]
@guihkx How can we sign and notarize our app with GitHub Actions using my Apple Developer certificates? I tried to do it on my machine but only managed to sign and not notarize. Also, I think for transparency's sake, it's better we use a clean environment.

**Comment by guihkx** [comment]
>How can we sign and notarize our app with GitHub Actions using my Apple Developer certificates?

I don't know yet. Can the process be done entirely via command line? If it can, then I think it should be feasible using '[secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets)' from GitHub Actions.

>Also, I think for transparency's sake, it's better we use a clean environment.

What do you mean by 'clean environment', exactly?

I'm also thinking that the signing and notarizing should only be done for release builds, because I'm not sure if it's possible for a person to send a malicious pull request and read your credentials...

**Comment by bjorn** [comment]
> I don't know yet. Can the process be done entirely via command line?

Yes, this is possible. I'm personally [using some helper actions](https://github.com/mapeditor/tiled/blob/95fe033aa1cb13e39d3a7a5fce55056afc0b4713/.github/workflows/packages.yml#L221-L246) for this, though they are somewhat unmaintained so I would recommend to try to find more up-to-date ones or to perform the needed commands in a script instead. I think the main issue is stapling, since it requires waiting on the notarization to be done. The action I am using is doing this by polling the notarization service for a while.

> What do you mean by 'clean environment', exactly?

That would be the CI environment, as opposed to his local machine. :-)

> I'm also thinking that the signing and notarizing should only be done for release builds, because I'm not sure if it's possible for a person to send a malicious pull request and read your credentials...

It isn't possible for PR builds to access the secrets, but that does mean we should limit this to our own builds, to avoid CI errors.

**Comment by nuttyartist** [comment]
> That would be the CI environment, as opposed to his local machine. :-)

Yes.

> I don't know yet. Can the process be done entirely via command line? If it can, then I think it should be feasible using '[secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets)' from GitHub Actions.

Ah great. Then I will create the appropriate secrets.

**Comment by guihkx** [comment]
@bjorn Gotcha. Thanks for the link, I'll take a look.

@nuttyartist I'll experiment locally, once I get it working I can send a pull request.

**Comment by nuttyartist** [comment]
@guihkx Perfect.

**Comment by dehesselle** [comment]
> I think the main issue is stapling, since it requires waiting on the notarization to be done. The action I am using is doing this by polling the notarization service for a while.

That's the case with the older `altool` which is being deprecated. The newer `notarytool` supports a synchronous mode where it blocks until the notarization process has been completed.  
full disclosure: I haven't transitioned to `notarytool` myself yet, but this is what I've read about it.

**Comment by bjorn** [comment]
In the meantime I've updated the Tiled builds to no longer use the unmaintained helper actions and just use the available tools directly: https://github.com/mapeditor/tiled/blob/b32f4152833e2f4481fd325e8a527fa6c2bdc694/.github/workflows/packages.yml#L228-L251

I don't know if there may be cleaner ways for some of these, but maybe it helps with setting this up for Notes.
