### ISSUE TITLE
Usablity issues on Linux

### ISSUE THREAD

**Issue by Yasand123** [nuttyartist/notes#450]
This is an amazing note-taking application, simple yet efficient. Unfortunately I found some bugs/usability issues on Linux that hinder the overall experience. I understand this is a work-in-progress and I'm sure the devs are aware, but I'm mentioning these issues just in case they were overlooked/missed.

- When closing the window with `native window frame` enabled, it actually closes the app instead of minimizing to systray.
- Left clicking on the tray icon doesn't restore the window, you'd have to right click to bring up the context menu and then click on _Show notes_.
- ~~`Win+N` doesn't work.~~
- ~~When restoring the window from the tray icon, it gets behind the current window, and not in front as you'd expect.~~
- ~~Upon hiding and unhiding the sidebar, the in-app _close, minimize and maximize_ buttons show up even when _native window frame_ is enabled.~~

OS: Arch Linux.
DE: KDE Plasma.

**Comment by guihkx** [comment]
>When closing the window with `native window frame` enabled, it actually closes the app instead of minimizing to systray.

There's an ongoing discussion in #278 about that.

>`Win+N` doesn't work.

I think the shortcut is actually <kbd>Win</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>, but AFAIK it only works correctly on Qt 5 builds (we now support Qt 6 as well). And judging by my tests, Notes has to be closed to the system tray too, I guess.


>Upon hiding and unhiding the sidebar, the in-app close, minimize and maximize buttons show up even when native window frame is enabled.

I think that was already fixed in #344.

**Comment by nuttyartist** [comment]
Hey @Yasand123!

> When closing the window with native window frame enabled, it actually closes the app instead of minimizing to systray.

Right now, only on Mac does the app hides when closing the window rather than quitting the app because this is the custom around macOS apps. I thought on Windows and Linux, the expected behavior is to quit the app. But since many are saying it will be better just to hide the app, I'm willing to reconsider this. I will reflect on this decision in #278.

> Win+N doesn't work.

That's weird; it should work.

> Left clicking on the tray icon doesn't restore the window, you'd have to right click to bring up the context menu and then click on Show notes.

That is true and very annoying! I'll open an issue about that. Thanks for reporting.

> Upon hiding and unhiding the sidebar, the in-app close, minimize and maximize buttons show up even when native window frame is enabled.

As @guihkx said, we already fixed this issue, just didn't deliver the updates yet. You can either wait until we ship version 2.1.0 or grab the latest (unstable) executables from GitHub Actions.

I'll add/update the mentioned issues. If you can give us more information regarding Win+N not working for you on a new issue, it will be helpful. I think we can close this and focus on the issues you mentioned separately. @Yasand123 What do you say?

**Comment by Yasand123** [comment]
Hello, @nuttyartist @guihkx, I just compiled from source and ineed the following issues are already fixed:
- Win+N doesn't work.
- When restoring the window from the tray icon, it gets behind the current window, and not in front as you'd expect.
- Upon hiding and unhiding the sidebar, the in-app close, minimize and maximize buttons show up even when native window frame is enabled.

Should've probably tested that first, I apologize. I will update the issue accordingly. And I'm glad that the remaining issues are being worked on.

**Comment by nuttyartist** [comment]
Great 👍 So #278 and #452 are opened for your remaining issues.

**Comment by Yasand123** [comment]
> Great +1 So #278 and #452 are open for your remaining issues.

Thank you. I'm closing this for now.
