### ISSUE TITLE
Improvements for clicking external links (local and web)

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#459]
Thanks to @kir-gadjello work in #430 we now support clicking external links (local and web).

Although two main issues remain:

1. The mouse cursor icon doesn't change unless the document is being focused on.
![image](https://user-images.githubusercontent.com/16375940/216930660-c7088de9-5740-44c6-b3f2-cc60dd842981.png)

@bjorn suggested we can solve it in this way:

> Since this is handled entirely within the widget, it should be possible to just override `mouseMoveEvent`, `mousePressEvent` and `mouseReleaseEvent`. For the `mouseMoveEvent` to get delivered, it may be necessary to set the [`mouseTracking`](https://doc.qt.io/qt-6/qwidget.html#mouseTracking-prop) property.

> A global event filter may still be needed for handling keyboard modifier keys, if we want them to change the cursor immediately and when the widget is not focused.

2. Also, as @bjorn noted, some more optimizations are possible:

> Another thing to note is that it should not be necessary to parse the entire note to collect all the URLs and then to iterate all these URLs to find out which one currently contains the cursor. Instead, one could for example get the cursor at the mouse position using [cursorAtPosition](https://doc.qt.io/qt-6/qtextedit.html#cursorForPosition), then use cursor.block().text() and search only this part of the text for URLs.
>
> We might also try to use QTextEdit::anchorAt, if we are able to tell Qt where the anchors actually are.

**Comment by bjorn** [comment]
> 2\. Also, as @bjorn noted, some more optimizations are possible:

While optimizations are certainly possible, I just want to note that the optimization I mentioned (only searching the hovered block of text) appears to have been already done in the following bit of code:

https://github.com/nuttyartist/notes/blob/bf1f62ec7d1db93f0df31d1e07ddf69bda0bec22/src/customdocument.cpp#L140-L143

Not sure how I missed that. Other optimizations that could be done are to reuse `QRegularExpression` instances and to combine `parseMarkdownUrlsFromText` and `getMarkdownUrlAtPosition` into a single function since then one could avoid the allocation of the `urlMap`.

**Comment by zjeffer** [comment]
> Not sure how I missed that

@bjorn You didn't miss anything, I added that improvement based on your comment :) 

You can see the changes in this PR: https://github.com/nuttyartist/notes/pull/552

**Comment by nuttyartist** [comment]
Oh, indeed! We can close this issue as both points have been adressed.

**Comment by bjorn** [comment]
> You can see the changes in this PR: #552

Hmm, I still think I missed it, because that PR does not change the relevant section, it was already just searching only the block of text under the cursor before that change:

https://github.com/nuttyartist/notes/blob/08b3dbdd738ed77d920b8d8ca9eb222a6a5e465c/src/customdocument.cpp#L124-L128

Anyway, it doesn't matter, this issue could be closed at least. :-)
