### ISSUE TITLE
Issues on Linux?

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#489]
Testing version 2.1.0, I'm not sure if it's just on the distro I've tested (Elementary OS 6), everything seems to work well apart from these two issues:

1. I can't run the QT 6 appimage (I get the following error from in terminal), although Qt5 works well:

```
/tmp/.mount_Notes_zZcQgr/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Notes_zZcQgr/AppRun.wrapped)
/tmp/.mount_Notes_zZcQgr/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Notes_zZcQgr/usr/bin/../lib/libQt6Core.so.6)
/tmp/.mount_Notes_zZcQgr/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Notes_zZcQgr/usr/bin/../lib/libglib-2.0.so.0)
/tmp/.mount_Notes_zZcQgr/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Notes_zZcQgr/usr/bin/../lib/libsystemd.so.0)
/tmp/.mount_Notes_zZcQgr/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_Notes_zZcQgr/usr/bin/../lib/libsystemd.so.0)
```

2.  The app icon looks blurry (at least on Elementary).

![Screenshot from 2023-02-20 21 44 07](https://user-images.githubusercontent.com/16375940/220203634-a2612fbb-c7cf-4dbf-ad19-f3c66d62602e.png)

BTW, seems to work well on macOS.
I'll test on Windows tomorrow as well.

@guihkx

**Comment by guihkx** [comment]
I'm not familiar with elementaryOS, but based on my Google search, version 6 is based on Ubuntu 20.04 Focal Fossa.

And Ubuntu 20.04 already ships [glibc 2.31](https://packages.ubuntu.com/source/focal/glibc), so none of these errors shouldn't even be showing up.

So either I'm completely wrong, or perhaps you're using an older version of elementary. Can you please double check with:

```
cat /etc/os-release
```

Regarding the blurry icon, it seems like elementaryOS itself is choosing a low-resolution icon, because we definitely include the icon in much higher resolutions (including a .svg).

You can verify this by extracting the AppImage using a terminal:

```
./Notes-*.AppImage --appimage-extract
```

And then navigating to `squashfs-root/usr/share/icons/hicolor` to browse all icons we include.

And I don't see that on GNOME 43 either:

![image](https://user-images.githubusercontent.com/626206/220204901-826062b4-30a2-45be-90ca-bcf1ba672394.png)

**Comment by guihkx** [comment]
By the way, were you able to resize the window while in frameless mode?

**Comment by nuttyartist** [comment]
> By the way, were you able to resize the window while in frameless mode?

Yes, although the custom code is not perfect (maybe the margins are too big and so the resizing start too close into the app), but it works.

> Can you please double check

Sure I'll double check now.

**Comment by guihkx** [comment]
>Yes, although the custom code is not perfect (maybe the margins are too big and so the resizing start too close into the app), but it works.

Oh wow. That definitely surprises me. As I demonstrated in #492 (first video), I can't even make the cursor handle to resize the window show up... :/

>Sure I'll double check now.

Thanks. It's also possible that elementaryOS is using some packages from Ubuntu 20.04, but decided to stay on an older version of glibc, for whatever reason...

In that case, there's not much we can do here except recommend users to use the Qt 5 AppImage, because Qt 6 requires at least Ubuntu 20.04.

**Comment by nuttyartist** [comment]
No, you were right! I was using Elementary OS 5. Sorry about that. 

> You can verify this by extracting the AppImage using a terminal:

Yep, I can see that. I guess we can figure it out some other time.

> Oh wow. That definitely surprises me. As I demonstrated in https://github.com/nuttyartist/notes/pull/492 (first video), I can't even make the cursor handle to resize the window show up... :/

Yes, the resize cursor doesn't change until I press it, but it changes and starts resizing very early (not only at the edges of the app). Do you have the same behavior? I was about to create a video but shut the system down hah. Do you have the same behavior?

I guess we can close this issue.

**Comment by guihkx** [comment]
>Elementary OS 5. Sorry about that.

No worries. ^^

>Yep, I can see that. I guess we can figure it out some other time.

Sure. Perhaps we can investigate not installing lower resolution icons altogether.

Most Linux apps I see nowadays seem to only install 128x128, 256x256 and 512x512 icons anyway.

>Yes, the resize cursor doesn't change until I press it

At the top edge, yeah. On the left and right edges, not really... But even when they show up, I can't get the window to resize... :S
