### ISSUE TITLE
Pressing control changes cursor icon even if the cursor is not hovering on a link

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#534]
The cursor icon should change only upon hovering a link. This bug causes the cursor icon to change every time control is pressed.

![test](https://user-images.githubusercontent.com/16375940/225721742-58e18465-afb4-41e4-bcbb-28d14d08cd27.gif)

**Comment by bjorn** [comment]
It's not really a bug, but a missing feature. ;-)

Thing is, the code currently does not care at all whether you're above a URL. It simply changes the cursor on the press and release of Ctrl:

https://github.com/nuttyartist/notes/blob/d6d4581e0c24f136e42eb69c955e067076555ba7/src/customdocument.cpp#L38-L51

**Comment by zjeffer** [comment]
Is there no way to do this purely with native Qt stuff?

After a short search, I came across this: https://doc.qt.io/qt-6/qt.html#TextInteractionFlag-enum. Might be worth looking into?

**Comment by zjeffer** [comment]
https://stackoverflow.com/a/1576894/10180569

**Comment by bjorn** [comment]
Yes, the challenge with making those links clickable, is to actually make them links rather than just highlighted text. And that without disrupting normal text editing operations.

**Comment by zjeffer** [comment]
Do you mean the markdownhighlighter would interfere with the native Qt functionality for this?

**Comment by bjorn** [comment]
> Do you mean the markdownhighlighter would interfere with the native Qt functionality for this?

No, I mean that the native Qt functionality is based on parsing markup (like HTML or Markdown) to create links that are stored in the document as [`QTextCharFormat::anchorHref`](https://doc.qt.io/qt-6/qtextcharformat.html#anchorHref). But since our links are plain text to Qt and just styled as a link through the syntax highlighter, we can't rely on that functionality.

I've tried using `QSyntaxHighlighter::setFormat` to set a format with an anchor in the highlighter, but couldn't get it to work. I think this functionality is not supported through the syntax highlighter, since it does not modify the document.

Personally I expect we'll just need to fix the code that sets the mouse cursor to actually check whether there's a link below the cursor.
