### ISSUE TITLE
Feature Request: color/theme options

### ISSUE THREAD

**Issue by apulley** [nuttyartist/notes#58]
It might be nice to have the following theme and color options. Seems minor, but I think it would be a big win over mac-notes.

* Left rail (note list) background and font-color options
* Left rail current note highlight color--background and font-color (background is currently yellow)
* Main note writing area background and font-color options (including date header). Also, the faux-paper background/pattern can probably go (imo)
* Options to remove the "+" and "trash" icons (keeps things even more minimal--we have keyboard shortcuts)

**Comment by nuttyartist** [comment]
Notes is all about being simple. Because it all starts with the ambition of creating something that will just work, and everyone could use and understand in the most intuitive way. One of the ways to get there is to remove choice to make things simpler.

It's like when you go to a huge supermarket and there are all different kinds of things. There are so many options to choose from and you are starting to get frustrated. Wouldn't it be great if there was a guy in the supermarket telling you "Hey look THIS is the best cheese for you, this is the best pasta" etc.. etc..?

Sure, some people won't like a thing or two from what this guy would tell them. And some just like to be hours in the supermarket, gracefully looking at all the available options.
But for the most part, most of the people will admire the way everything just works. 

So no, we are not going to give the option for choosing all that stuff, but this decision is due to the signifance of our beliefs.

We might want in the future to have some **minor** customization options, but we'll look into it in future versions. Yet you're more than welcome to argue about the default choice of colors/fonts/size etc...

----------------------------------------------------------------------------------------------------------------------------------------
And I want to take this oppurtinity to talk about the similiarites to the Mac OS X Notes app.

I never intended to mimic their style as a whole. My intention was to make a great note-taking app. And so, one of the ways I saw that would help me get there is to use some of the design decisions of their note-taking app. When we have that vision of creating the best note-taking app, the approach to get there may differ from time to time, and evolve by the belief of creating a great writing experience. It is not creating a Mac osx like app (or any other app) that motivates us.

The thing is, the promise of Notes is much bigger than what we currently have. Through the future versions it would shape itself into a new, much better form. What we are trying to do now, is to create the base, the core-expirience, and to learn throughtout the way how to empower people more. 

Now it's about creating a very fine degree of the foundation that everything will be built on top. From the inside - making sure are code and technology get to a very strong base, and the outside - making sure the expirience is so refined that everything Notes should do till 1.0.0 is done perfectly. Both have **vastly** improved since the inception of Notes, and mainly since it was open to the public through amazing contributers.

**Comment by apulley** [comment]
Thanks for the response and consideration @nuttyartist! Much respect to your thoughts on how this application should evolve. I look forward to seeing how things progress. :+1:
