### ISSUE TITLE
Windows build issues - Qt Quick doesn't work via installer, app isn't deleted via uninstaller

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#595]
Currently we have only two issues with our windows build/packaging:

1. Qt Quick works using the singular packages (Qt5/Qt6) but not via the installer for some reason.
2. From quick inspecting it seems like the uninstaller doesn't delete "Program Files://Notes" folder. Why is that?

@guihkx any idea?

**Comment by nuttyartist** [comment]
I just tested and Qt Quick works in `master`'s installer. But not in #589's installer.

Tho both uninstallers doesn't remove  `C:\Program Files\Notes`
They leave the following folders but they are all empty.
![Screen Shot 2023-07-07 at 5 03 04 PM](https://github.com/nuttyartist/notes/assets/16375940/db75553b-c08d-4de4-964a-526a622f9ed6)

**Comment by nuttyartist** [comment]
For 1. How can I check the errors via `cmd`? Simply executing `Notes.exe` doesn't seem to cut it.

**Comment by guihkx** [comment]
> They leave the following folders but they are all empty.

Odd... It could be because we're using an wildcard (`*`) to include files from that directory, but I'll check when I have some time.

> For 1. How can I check the errors via `cmd`? Simply executing `Notes.exe` doesn't seem to cut it.

I believe that on Windows you have to attach a console window to the process. I've done [this](https://stackoverflow.com/a/41701133) in the past, but I'm sure there's a "proper" way to do it.

**Comment by nuttyartist** [comment]
I've mingw installed, and I can't get errors trying to install msvc for some reason (our installer's binary is built with msvc). Can you test it on your machine?

**Comment by guihkx** [comment]
I tested the installer from [current master](https://github.com/nuttyartist/notes/actions/runs/5258293486), and at least on my Windows 10 machins all folders are getting removed completely:

https://github.com/nuttyartist/notes/assets/626206/c547292f-9ae0-42b0-8a67-d35e2410e031

Regarding QtQuick being broken on the installer from #589, I have found what the problem is and I'll push a commit to fix it.

**Comment by nuttyartist** [comment]
> I tested the installer from [current master](https://github.com/nuttyartist/notes/actions/runs/5258293486), and at least on my Windows 10 machins all folders are getting removed completely:

What if you try to uninstall using #589 installer?

> Regarding QtQuick being broken on the installer from https://github.com/nuttyartist/notes/pull/589, I have found what the problem is and I'll push a commit to fix it.

Yay, it works now, thanks!

**Comment by guihkx** [comment]
> What if you try to uninstall using #589 installer?

Same thing using the installer from [this job](https://github.com/nuttyartist/notes/actions/runs/5492421528): All folders are removed. 🤷‍♂️ 

https://github.com/nuttyartist/notes/assets/626206/021c18f1-0c3d-48d0-a31c-bfedbf6333a0

**Comment by nuttyartist** [comment]
Weird! Anyway, it doesn't seem like a major issue, but if any users will report it, I'll reopen this issue. I guess we can close this for now. Thanks, @guihkx.
