### ISSUE TITLE
 Some requests 

### ISSUE THREAD

**Issue by AbdullZ7** [nuttyartist/notes#63]
- Support RTL
![RTL Test](https://cloud.githubusercontent.com/assets/5797362/15536042/71bda4f4-2278-11e6-8e7c-d98fe1f9d5e5.png)
- adding an option to be able to change the "Interface scale"
- Sync with dropbox ,box or google drive
- Support "Hijri calendar" 
- Adding Always on top option on windows
- Warn the user before deleting the note and add "recover the notes" button
-Use this Arabic font especially with Linux: [Noto Naskh Arabic](https://www.google.com/get/noto/#naskh-arab) it supports (Arabic, Persian, Uighur and Urdu) Font characters

**Comment by theshadowx** [comment]
Just to let you know that all the notes deleted are stored in (if you are in linux) ~/.config/Awesomeness/Trash.ini

> adding an option to be able to change the "Interface scale"

the problem here is that the app doesn't use the default decoration that's why you don't see scaling cursor at the border. But you can maximize the app by either double click on the app or using the green button

> Sync with dropbox ,box or google drive

Future releases

> Support "Hijri calendar"

The app should use the local calendar (maybe this can be added with no problem)

> Adding Always on top option on windows

yes indeed this should be added not only in windows but in all OSes

> Warn the user before deleting the note and add "recover the notes" button -Use this Arabic font especially with Linux: Noto Naskh Arabic it supports (Arabic, Persian, Uighur and Urdu) Font characters

well the text editor is in a rich media mode, meaning if you choose your keyboard language as arabic it will write from RTL, but sure the note list should support RTL



![notes_207](https://cloud.githubusercontent.com/assets/976569/15539440/64992760-227a-11e6-80b8-a9f9ef8ac1f4.png)

**Comment by nuttyartist** [comment]
Hey AbdullZ7, thanks for the feedback!

1. I thought about RTL languages, as of right now (when the noteView is on the left side) RTL languages doesn't show from right to left, so that should be fixed. I thought about giving the option to change the place of noteView to the right, but I haven't figured yet a good way to do it without compromising the user experience. We don't want to have settings for Notes, when you give people settings option they are going to procrastinate rather than focusing on the writing. So you're welcome to share ideas, I will keep on thinking about a way to do it right.
2. What do you mean by  "Interface scale"?
3. Like theshadowx said, we are working on syncing capabilities for future releases, but we are not planning on syncing with 3rd party services, but to make a very fine and simple syncing experience like that of Simplenote.
4. That will be solved in part of making the translation and localization system, see #10.
5. "Always on top" is an interesting feature, we'll add that to our wishlist as a new "issue" and see how we can integrate it in our app in a way that doesn't clutter the app and without using settings.
6. In future releases, there will be a "Trash" folder where you can see all of your deleted notes. We think the user should easily and fast remove there notes yet easily and fast recover them, so that what we're aiming fo the future. Like theshadowx said, right now we implemented a "secret" database for people who might delete their notes mistakenly and want to recover them.
7. About the Arabic font, it seems like a nice font, we'll look into integrating it in our app for Arabic languages.

I'll create new "issues" so we can tackle the problems and the suggestions you made, thanks again.

**Comment by AbdullZ7** [comment]
- The app should use the local calendar (maybe this can be added with no problem)

No it doesn't use the OS default calendar 

- but I haven't figured yet a good way to do it without compromising the user experience.

In the right click menu ! .. if it's possible.

- What do you mean by "Interface scale"?

I think it's called DPI .. in the high resolution monitors 4k and 8k the app's window and it's icons will be too small.

- About the Arabic font

The app doesn't support "Kashida" https://en.wikipedia.org/wiki/Kashida
![gxal4cy 1](https://cloud.githubusercontent.com/assets/5797362/15662988/89447532-26fe-11e6-875e-7ba9d512a6b1.png)

also here is anther font you can use it:
http://www.amirifont.org/

**Comment by nuttyartist** [comment]
> No it doesn't use the OS default calendar

He meant it "**should** use the local calendar", we will take care of that when tackling this issue #10 .

> In the right click menu ! .. if it's possible.

What right click menu? Where does the user should click?

> I think it's called DPI .. in the high resolution monitors 4k and 8k the app's window and its icons will be too small.

Oh alright, we will take care of that on #39.

> The app doesn't support "Kashida"

Correct me if I'm wrong, but from what I understood Kashida is a technique for justification alignment (making all the lines align with each other), but it achieves that not by changing the space between words but by making some certain letters longer, right?
Anyway, I believe justification alignment shouldn't be a default option that comes with the app, but rather an option, yet we don't have that option right now (for all the languages). 
If we'll decide to put an option for justification alignment in future releases we'll surely support Kashida!

> also here is anther font you can use it:

Thanks! we'll consider the fonts you proposed and add the chosen one when will complete the support of other languages.

**Comment by AbdullZ7** [comment]
- What right click menu? Where does the user should click?

In this yellow area maybe, if the user clicked on the right mouse button in this area a dropdown menu will show up with the application settings in it:
![ufxqxyt 1](https://cloud.githubusercontent.com/assets/5797362/15695066/16372df6-27ac-11e6-96c6-42e759ae53c0.png)

- The app doesn't support "Kashida"

It's character make the word longer .. in Arabic you can't put space between letters to make the word longer you should use "Kashida" instead of space.  
![untitled-1](https://cloud.githubusercontent.com/assets/5797362/15697602/5778ea1c-27c4-11e6-8a8f-c11cd35dc3d5.png)

**Comment by nuttyartist** [comment]
> In this yellow area maybe, if the user clicked on the right mouse button in this area a dropdown menu will show up with the application settings in it:

I don't think that's the right place to do it. I tell you what, in the future release we'll have a menu bar button (3 dots button) and so I think it will be a better place for it there.

> It's character make the word longer .. in Arabic you can't put space between letters to make the word longer you should use "Kashida" instead of space.

Alright, I wonder if it's something that should be supported in the font or something on our side in the app. Anyway, we'll look to solve that in #10.
