### ISSUE TITLE
Synchronization across devices

### ISSUE THREAD

**Issue by audiofeature** [nuttyartist/notes#75]
Notes would be only really useful to me if it could sync across devices and platforms:

Keep the notes in sync on my Linux machine and my Mac laptop, ideally also mobile apps, etc.

Even better than sync between devices running this open-source Notes application would be also a sync with Apple's notes for Mac (through IMAP or iCloud or other).

**Comment by nuttyartist** [comment]
Syncing is a great feature we're planning to do in our future releases, but we're not planning on syncing with 3rd party services. We strive for the most straightforward and simple way of doing syncing which would work only with our app, the way Simplentoe does. That way, everything will "just work" without the user need to change or decide anything.

So, we're not going to support syncing with Apple's Notes app (or any other 3rd party app), but our app will support syncing between our app across devices flawlessly when we'll make it.

**Comment by gersoto** [comment]
Just a Question, 

Why don't we think, apart from syncing between different instances of this application, in different devices (Different computers), to save a raw-text copy, maybe plain text, into Gmail or Dropbox, and keep this copy synced in order to "read" the content wherever we are, from the device we have in a moment

**Comment by nuttyartist** [comment]
We need to always look for the best option for the user. The best one would be to have a version of our app on all the major platforms in mobile and desktop (and maybe web too) and sync flawlessly between all of them, and this is what we are planning to do.

What you're suggesting isn't part of that optimal solution and experience for our users, it sounds more like an half-baked solution for getting your notes to work *now* on your other platforms, which, I understand, because it's a feature I long for too. 

The ability to record your thoughts wherever you are, whenever you are is the ultimate form Notes should take. But we'll need to do it right.

**Comment by gersoto** [comment]
Ok, thank you for your answer, it makes sense it will need to have a good sync mechanism, across different devices and systems using the application but, what I meant, or proposed is a secondary way to access to this notes, read only, from a third party system/application.

Thank you so much!

Enviado desde mi iPad
