### ISSUE TITLE
imap syncing

### ISSUE THREAD

**Issue by davewhitney** [nuttyartist/notes#93]
Can you add support for imap syncing?  My email provider also supports imap notes syncing, it's a critical feature for me.

Thanks for your consideration!

Regards,

Dave

**Comment by nuttyartist** [comment]
Hey Dave,

We're not planning on supporting notes syncing with email. It's just too big of a scope for our app to operate on, it'll confuse our users because the more option for settings there would be, the more they'll feel not in control, thereby they well become confused or frustrated.

May I ask you why is this feature important to you? Is it because you want to access your notes through the browser? Cause if so, we might plan to have a web app someday (yet not sure).

We want to do best for our users, some decision won't appeal to some people. I hope you 'll love Notes as a whole.

Thanks!
